language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
install: pip install -q Django==$DJANGO_VERSION djangorestframework>=3.6,<3.8
script: python setup.py test
